# Generated by Django 4.0.3 on 2022-04-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo:')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_titulo', models.DateTimeField(verbose_name='Data do evento:')),
                ('data_criacao', models.DateTimeField(auto_now=True, verbose_name='Data de criação:')),
            ],
            options={
                'db_table': 'evento',
            },
        ),
    ]
